### ISSUE TITLE
Small documentation issues for train&test ResNet-50 (without OHEM)

### ISSUE THREAD

**Issue by ngaloppo** [Orpine/py-R-FCN#1]
Thanks for making this code available. I am trying to train & test ResNet-50 (without OHEM). Here are the issues I have found in the docs: 

- Have to run `make` in `$FRCN_ROOT/lib/` folder for `cython_bbox` compilation
- Before running the training script, make sure your add `$CAFFE_ROOT/python` to your `PYTHONPATH` environment variable
- The training script takes an extra argument for the dataset (`pascal_voc` or `coco`). This is not documented in the README, but it is documented in the script itself.
- Despite what is stated in the README, `test.agonistic` and `train.agonistic` are set to True by default by the `cfgs/rfcn_end2end.yml`

**Comment by Orpine** [comment]
Hi @ngaloppo , thanks for your attention, I indeed made something unclear. And I followed your advice, modified the document. In fact, `AGONISTIC` is set to False by default, you could check lib/fast_rcnn/config.py, but I provide a configuration file for you, you could just use this file without any modification.

Can you run this code now? I'm looking forward to seeing someone who run this code successfully too. And my result shows that the result of end-to-end training is not as good as 4-step training. It seems that  when you use joint training, poor rois that rpn produces at the very beginning will "confuse" OHEM, but I'm not sure, it needs more time to figure it out.

**Comment by ngaloppo** [comment]
Hello @Orpine. Thanks again for providing this code. Regarding the `AGONISTIC` setting, I think my point is that if the user doesn't do anything special, the script will automatically use the `experiments/cfgs/rfcn_end2end.yml` file, and so `AGONISTIC` is automatically set to `True`. Just a minor point though... 

I was able to train & test. I'm getting a mean-AP of 0.7405 for VOC2007 test data on the VOC2007+2012 training data. I didn't apply OHEM during training, so I can't directly compare to the results you have posted in the README, but I believe that this is a great result. Would you agree?

**Comment by xiaoxiongli** [comment]
@ngaloppo yes, I agree^_^, but unfortunately, I am not familiar with python...

**Comment by Orpine** [comment]
@ngaloppo Yes, I think that is a reasonable result, and I found that sometimes 110k achieves better results than 120k, I don't know why, maybe because I use 12000/2000 rois instead of 6000/300 rois in the original code, I'm trying to figure it out, and you can check the 110k result by run test_net.py individually :).
