### ISSUE TITLE
What is the benefit of using OHEM？

### ISSUE THREAD

**Issue by supersuper-qian** [Orpine/py-R-FCN#11]
In readme, author said that OHEM need all rois to select the hard examples.
What is the benefit of using OHEM specifically？And how the Efficiency and effectiveness will changed？
Thank you.

**Comment by Orpine** [comment]
OHEM is cost-free, and we usually get 1 to 3 points gain by using it. The key idea is that we select hard examples rather than random sample examples. You could check https://arxiv.org/abs/1604.03540 for more details.

**Comment by supersuper-qian** [comment]
@Orpine 
Thank you for your reply.
