### ISSUE TITLE
How to train the py-R-FCN using my own data?

### ISSUE THREAD

**Issue by supersuper-qian** [Orpine/py-R-FCN#13]
I am trying to train the py-R-FCN using my own data, and my data has only 2 categories. I changed the codes referring to faster-RCNN.
But what should I do with train_agonistic.prototxt and test_agonistic.prototxt? I have changed param_str: "'num_classes': 21 to param_str: "'num_classes': 3 in line 11 in  train_agonistic.prototxt.
Should I change num_output: 1029 #21*(7^2) cls_num*(score_maps_size^2) in line 3736 and output_dim: 21 in line 3790?
Anything else?
Thank you!

**Comment by supersuper-qian** [comment]
I have seen the same problem and I will close it.

**Comment by Timonzimm** [comment]
What did you do finally? I'm getting a it lost at the moment trying to do the same, see issue #66
