### ISSUE TITLE
About R-RCN+ resnet ensemble

### ISSUE THREAD

**Issue by supersuper-qian** [Orpine/py-R-FCN#14]
I have noticed that R-FCN+ resnet ensemble have achieved the best result in VOC 2012. So what the difference between resnet and ensenmble? And is R-FCN used in VOC2012 exactly the same with this py-R-FCN?

**Comment by Orpine** [comment]
Ensemble means to use several model to get predictions and combine them to get better results. This joint training version will deliver slightly lower mAP than official version. So if your goal is to get mAP as high as possible, I suggest you use the official implementation with 4 step training.
