### ISSUE TITLE
What's the benefit of warmup?

### ISSUE THREAD

**Issue by CPFLAME** [Orpine/py-R-FCN#15]
It's so nice of you to share the code with us,it's a wonderful work!
  I know about ohem which is to select hard examples and re-train them,but what's the use of warmup?
  waiting for your apply!

**Comment by Orpine** [comment]
That is one of my attempts to solving the problem that joint training with OHEM will deliver slightly lower mAP by using a smaller learning rate at the beginning. But I failed, so please just ignore it.
