### ISSUE TITLE
Error when I set IMS_PER_BATCH: 2 in the rfcn_end2end_ohem.yml

### ISSUE THREAD

**Issue by noirblack** [Orpine/py-R-FCN#17]
I get this error when  I set IMS_PER_BATCH: 2 in the rfcn_end2end_ohem.yml
F1025 15:56:37.929327  3406 loss_layer.cpp:19] Check failed: bottom[0]->num() == bottom[1]->num() (2 vs. 1) The data and label should have the same number.
*** Check failure stack trace: ***
--------------------------------------------------------
Is that other setting I should change when I want to train 2 images per batch?

**Comment by Orpine** [comment]
Please keep IMS_PER_BATCH to 1 since RPN only support 1 image every iteration. You could modify iter_size in solver prototxt, it is equivalent to IMS_PER_BATCH.
