### ISSUE TITLE
Error when I train, I get "has no attribute 'set_random_seed' "

### ISSUE THREAD

**Issue by zhangjunior** [Orpine/py-R-FCN#18]
Hi,
Thanks for you code. I have run demo successfully. 
But when I run **train_net.py**, the error appeared.
 File **"tools/train_net.py"**, line 100, in 
caffe.set_random_seed(cfg.RNG_SEED)
AttributeError : 'module' object has no attribute 'set_random_seed'**
 
My caffe is [daijifeng's caffe-rfcn](https://github.com/daijifeng001/caffe-rfcn)

**Comment by Orpine** [comment]
Please follow the README and use [Microsoft-version Caffe(@commit 1a2be8e)](https://github.com/Microsoft/caffe/tree/1a2be8ecf9ba318d516d79187845e90ac6e73197), the official caffe-rfcn does not support set_random_seed, as you can see in https://github.com/Microsoft/caffe/blob/master/python/caffe/_caffe.cpp#L54 and https://github.com/daijifeng001/caffe-rfcn/blob/r-fcn/python/caffe/_caffe.cpp#L53

**Comment by zhangjunior** [comment]
Thank you!
