### ISSUE TITLE
question about the bottom of rpn_conv/3x3

### ISSUE THREAD

**Issue by neodooth** [Orpine/py-R-FCN#21]
hi,
For resnet-50, in train_agnostic.prototxt, rpn_conv/3x3 is connected to res5c, while in the ohem version rpn_conv/3x3 is connected to res4f, and in test_agnostic.prototxt, it's connected to res4f as in the ohem version. Is this a typo or something?

**Comment by Orpine** [comment]
Yeah, it is a kind of typo. In the first version the rpn_conv/3x3 layer was connected to res5c, and I moved it to res4f/res4b22 in the later version.  I modified it in the OHEM-version prototxt, but I forgot to modify train_agnostic.prototxt . Actually there is little difference between two version, you could either change the train prototxt or test prototxt to be consistency.
Thanks for your reminder, this issue has been fixed.
