### ISSUE TITLE
About running it on Ubuntu

### ISSUE THREAD

**Issue by SpecialM2580** [Orpine/py-R-FCN#23]
I followed most of your steps(caffe is copyed from py-faster-rcnn), yet it shows :
```
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 7106:25: Message type "caffe.LayerParameter" has no field named "psroi_pooling_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F1106 19:37:52.764528  5270 upgrade_proto.cpp:68] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /home/yyc/Documents/py-R-FCN-master/models/pascal_voc/ResNet-101/rfcn_end2end/test_agnostic.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)
```
Am I doing it wrong? I looked up "psroi_pooling", yet I didn't find the layer's definition anywhere, plz help~

**Comment by Oh233** [comment]
Please use the corresponding caffe mentioned in the README.md https://github.com/Microsoft/caffe/tree/1a2be8ecf9ba318d516d79187845e90ac6e73197

**Comment by SpecialM2580** [comment]
Sorry, I totally should followed all your steps TAT, it was merged in to that version of caffe...I thought you guys use the python interface to create a new layer. My bad...Looking forward the new caffemodel .
