### ISSUE TITLE
what is the function of box_annotator_layer?

### ISSUE THREAD

**Issue by litingfeng** [Orpine/py-R-FCN#24]
After reading the code in` box_annotator_layer.cu `, I still have no idea what is the purpose of this layer? Is it used to select 128 ROIs to backpropagate? If so, why is the top->num  not 128?

These are the output of the shapes:
`gt_inds  (2,)`
`all_rois shape:  (138, 5)`
`gt_boxes shape:  (2, 5)`
`rois_per_image  inf`
`fg_rois_per_image  inf`
`I1109 21:24:01.311867 32751 box_annotator_ohem_layer.cu:71] bottom_rois 140`
`I1109 21:24:01.311887 32751 box_annotator_ohem_layer.cu:72] bottom_loss 140`
`I1109 21:24:01.311890 32751 box_annotator_ohem_layer.cu:73] bottom_labels 140`
`I1109 21:24:01.311893 32751 box_annotator_ohem_layer.cu:74] num_imgs 1`
`I1109 21:24:01.311895 32751 box_annotator_ohem_layer.cu:75] roi_per_img_ 128`
`I1109 21:24:01.311898 32751 box_annotator_ohem_layer.cu:76] top_labels 140`
`I1109 21:24:01.311916 32751 box_annotator_ohem_layer.cu:77] top_bbox_loss_weights 140`
`gt_inds  (2,)`
`all_rois shape:  (300, 5)`
`gt_boxes shape:  (2, 5)`
`rois_per_image  inf`
`fg_rois_per_image  inf`
`I1109 21:24:01.395092 32751 box_annotator_ohem_layer.cu:71] bottom_rois 302`
`I1109 21:24:01.395112 32751 box_annotator_ohem_layer.cu:72] bottom_loss 302`
`I1109 21:24:01.395129 32751 box_annotator_ohem_layer.cu:73] bottom_labels 302`
`I1109 21:24:01.395133 32751 box_annotator_ohem_layer.cu:74] num_imgs 1`
`I1109 21:24:01.395135 32751 box_annotator_ohem_layer.cu:75] roi_per_img_ 128`
`I1109 21:24:01.395138 32751 box_annotator_ohem_layer.cu:76] top_labels 302`
`I1109 21:24:01.395140 32751 box_annotator_ohem_layer.cu:77] top_bbox_loss_weights 302`
`gt_inds  (2,)`
`all_rois shape:  (216, 5)`
`gt_boxes shape:  (2, 5)`
`rois_per_image  inf`
`fg_rois_per_image  inf`
`I1109 21:24:01.517530 32751 box_annotator_ohem_layer.cu:71] bottom_rois 218`
`I1109 21:24:01.517550 32751 box_annotator_ohem_layer.cu:72] bottom_loss 218`
`I1109 21:24:01.517554 32751 box_annotator_ohem_layer.cu:73] bottom_labels 218`
`I1109 21:24:01.517556 32751 box_annotator_ohem_layer.cu:74] num_imgs 1`
`I1109 21:24:01.517559 32751 box_annotator_ohem_layer.cu:75] roi_per_img_ 128`
`I1109 21:24:01.517561 32751 box_annotator_ohem_layer.cu:76] top_labels 218`
`I1109 21:24:01.517563 32751 box_annotator_ohem_layer.cu:77] top_bbox_loss_weights 218`

**Comment by Oh233** [comment]
This layer is added to achieve OHEM. 

It will select top 128 ROIs (set by roi_per_img) according to loss. And annotate other ROI labels by -1 (set by ignore_label). Therefore in the successive layers, ROI with label -1 are ignored and therefore only the top 128 ROIs will contribute to the loss. 

Similar to bbox_regression branch.
