### ISSUE TITLE
py-faster-rcnn support multiple imdb with --imdb voc_2007_trainval+voc_2012_trainval

### ISSUE THREAD

**Issue by KeyKy** [Orpine/py-R-FCN#26]
Since py-faster-rcnn does not support multiple training datasets, we need to merge VOC 2007 data and VOC 2012 data manually. Just make a new directory named VOC0712, put all subfolders except ImageSets in VOC2007 and VOC2012 into VOC0712(you'll merge some folders). I provide a merged-version ImageSets folder for you, please put it into VOCdevkit/VOC0712/

To my knowledge, py-faster-rcnn support multiple imdb with --imdb voc_2007_trainval+voc_2012_trainval

**Comment by Orpine** [comment]
Thanks for your reminder, I should notice this :(. I think I would fix it in the next commit.
