### ISSUE TITLE
Why the length of output bbox is 8 ? 

### ISSUE THREAD

**Issue by jay2002** [Orpine/py-R-FCN#3]
Thanks for this great work first.
I have question about the network structure, this is, why the length of output bbox is 8? If we use class-agonistic bbox regression, the length of bbox vector should be 4.  Are the first 4 values regressed for background, and the last 4 values regressed for objects?

**Comment by Orpine** [comment]
Yes, in agonistic bbox regression it is actually a 2-class bbox regression, the first 4 dims is for background and the last 4 dims are for foreground. In fact the first 4 dims will never be used.
