### ISSUE TITLE
How to visualize position-sensitive score maps

### ISSUE THREAD

**Issue by xxi511** [Orpine/py-R-FCN#34]
I want to visualize position-sensitive score maps as the paper show
how can I do this ?
I think the position-sensitive score maps are `rfcn_cls` right?
Thanks!

![image](https://cloud.githubusercontent.com/assets/10164640/20873093/412b3248-badf-11e6-91dc-c18ec1221df1.png)

**Comment by liyi14** [comment]
Exactly, @xxi511 , these position-sensitive score maps visualized in paper used `rfcn_cls` data blob. Assume you have already exported the `rfcn_cls` blob, you want to visualize `c`-th (begin with 0) class, and the score_map_size is `k`. You just need to visualize channels within `[c*k^2, (c+1)*k^2)`. Some normalization such as `softmax` or `scale` will help to improve the visualization quality.

**Comment by xxi511** [comment]
Hi @liyi14 
Let me check, the output dimension of `rfcn_cls` is (1029, 38, 50)
(38, 50) is feature map size, original image size is (375, 500) # (h, w)
1029 is 7 * 7 * 21
each ROI rectangle was divided into 7*7, like table below from 0 ~ 49

| 0 |1 |2 |3 |4 |5 |6 |
| ------| ------ | ------ | ------ | ------ |------ |------ |
| 7 |8 |9 |10 |11 |12 |13 |
| 14 |15 |16 |17 |18 |19 |20 |
...

`rfcn_cls[0, 0:21]` means 0 for class 0 ~ class 21
`rfcn_cls[0, 21:42]` means 1 for class 0 ~ class 21
or
`rfcn_cls[0, 0:49]` means class0 for 0 ~ 49    
`rfcn_cls[0, 49:98]` means class1 for 0 ~ 49     

I think the first is right, but the visualization result is confuse me, this is `rfcn_cls[0, 21*24:21*25]`
this is position map of center part
according to definition, indexes of dog and horse are 12, 13 (0 is background)
but the feature maps are low energ
Thanks!
![image](https://cloud.githubusercontent.com/assets/10164640/21323166/3f3b1e34-c657-11e6-9e33-42971c9f0fd1.png)

I used this [tutorial](http://nbviewer.jupyter.org/github/BVLC/caffe/blob/master/examples/00-classification.ipynb) to visualize feature map, the function `vis_square`

**Comment by xxi511** [comment]
OK, I got it
the arrange follow the classes, e.g. 49, 49, 49
`rfcn_cls[0, 0:49]` means class0 for 0 ~ 49
`rfcn_cls[0, 49:98]` means class1 for 0 ~ 49
 normalize range is `rfcn_cls[0, 0:49]`
![image](https://cloud.githubusercontent.com/assets/10164640/21356206/b9a8fcfe-c70b-11e6-81bc-92e213e60959.png)
