### ISSUE TITLE
why coco train_agnostic.prototxt has 21 classes instead of 81 classes?

### ISSUE THREAD

**Issue by liuchang8am** [Orpine/py-R-FCN#44]
Hi, 

https://github.com/Orpine/py-R-FCN/blob/master/models/coco/ResNet-101/rfcn_end2end/train_agnostic.prototxt#L11

I think coco detection has 80 classes, why the num_classes is 21 in this line (`param_str: "'num_classes': 21"` ) ?

**Comment by liuchang8am** [comment]
I compared the train_agnostic.prototxt files for coco and pascal_voc, and they turn out to be the same file. Did you upload the wrong file for coco dataset? @Orpine

**Comment by liuchang8am** [comment]
Yet what really confuses me is that even with the wrong train proto file, I can still get the rfcn_end2end model training, without any errors. I'm not an expert in detection, but I believe something is really wrong here.

**Comment by Orpine** [comment]
@liuchang8am That is a mistake, please use train_agnostic_ohem.prototxt since we just modified this prototxt for coco dataset.
