### ISSUE TITLE
HOW TO RETRAIN USING SNAPSHOT ：）

### ISSUE THREAD

**Issue by Designbook1** [Orpine/py-R-FCN#69]
Hi， @Orpine ,
       Now I'm training a very large dataset using the amazing rfcn network. Because the iterate time is 1500k,    it may break sometime, so I want to know how to retraining the network using snapshot?
 I try to add --snapshot output/resnet101_rfcn_ohem_iter_1000000.solverstate , but it doesn't work.
 can you help me ? anybody help?

**Comment by Orpine** [comment]
Hi, 
I suggest you use our new implementation https://github.com/msracver/Deformable-ConvNets. It supports multi-GPU training and could easily use snapshot to resume training.

**Comment by Designbook1** [comment]
@Orpine ok, I will try, and thank you for your suggestion .
