### ISSUE TITLE
Segmentation fault when running demo in CPU mode

### ISSUE THREAD

**Issue by FabHan** [Orpine/py-R-FCN#7]
```
./tools/demo_rfcn.py --cpu
```
leads to segmentation fault, after these lines
```
I0922 20:40:52.680196  4690 net.cpp:771] Ignoring source layer silence
I0922 20:40:52.680202  4690 net.cpp:771] Ignoring source layer loss
I0922 20:40:52.680209  4690 net.cpp:771] Ignoring source layer accuarcy
I0922 20:40:52.680217  4690 net.cpp:771] Ignoring source layer loss_bbox
```

I don't have GPU :(.

**Comment by Orpine** [comment]
I think this is because PSROIPooling layer only have GPU version. Since GPU plays a big role in deep learning, I suggest you buy a GPU to do some experiment. As I wrote in README, 4GB is enough for ResNet-50 :). If you really have no budget, you can implement CPU version by your own.
