### ISSUE TITLE
number of output channel of rfcn_bbox layer in train.prototxt 

### ISSUE THREAD

**Issue by ananddb90** [Orpine/py-R-FCN#74]
Hello @Orpine ,
I have a doubt in number of output channel mentioned in train_agnostic.prototxt under resnet-50/rfcn_end2end. 
As per my understand, number of output channel for rfcn_bbox layer should be equal to 4*cls_num*(k^2) which makes it 4*21*7*7 where as in prototxt its mentioned as 8*7*7. Could you please help me to know reason behind number 8?

thank you

**Comment by Orpine** [comment]
Because we use class-agnostic, so for bbox regression the cls_num is 2.

**Comment by 315386775** [comment]
@Orpine Why i use class-agnostic, but get the fllowing [error.](https://github.com/Orpine/py-R-FCN/issues/80) . Can you help me?
