### ISSUE TITLE
How to train on own dataset?

### ISSUE THREAD

**Issue by zxy1016** [Orpine/py-R-FCN#9]
Hi, i'm trying to train on my own dataset with different classes, when i revised the train.prototxt, i just revised three place[new conv layer:num_output; input_data:num_classes],is that right?

**Comment by Orpine** [comment]
Hi @zxy1016 ,
Besides prepare your own data, you need to modify two layers' num_output: "rfcn_cls", "psroipooled_cls_rois", and you needn't modify num_classes of  "input-data" layer since it is useless when using RPN.

**Comment by supersuper-qian** [comment]
@Orpine 
@Orpine 
But why have i trained it using my own dataset without changing "rfcn_cls" and "psroipooled_cls_rois"?(my categories are 2)
Does it have impact on accuacy?

**Comment by Timonzimm** [comment]
Hi, 
Could you please enlighten me on the part about preparing the data? I couldn't find any help reading the Readme
