### ISSUE TITLE
Merged folder for image set?

### ISSUE THREAD

**Issue by chriszhenghaochen** [Orpine/py-R-FCN#94]
I am trying to train VOC07 +VOC12 data and notice in your instruction, you mention that you provide the merged imageset for that. However looking through the repo, I didn't see that.

Would you mind re-sharing the link to download the folder, thank you very much. Or someone can link this to relevant closed issue, many thanks @YuwenXiong

**Comment by YuwenXiong** [comment]
Here, https://github.com/YuwenXiong/py-R-FCN/tree/master/ImageSets

But actually you could refer https://github.com/YuwenXiong/py-R-FCN/issues/26

**Comment by chriszhenghaochen** [comment]
thanks !!!
