### ISSUE TITLE
how to generate a solverstate?

### ISSUE THREAD

**Issue by muyue1238** [Orpine/py-R-FCN#95]
Hi  @YuwenXiong. When I use the code you provide to train on resnet-101, I found no solverstate file generated. It's bothering me because my server doesn't work well and it breaks down sometime. I've already restarted several times and it's killing me. So my question is how to generate a solverstate file so that I can continue my training without restarting from the very beginning? And I saw another issue where you mentioned another work of yours, but the situation is that I can't change my method to that new work, so it'll be very kind if you can answer my question.

**Comment by YuwenXiong** [comment]
Please check your code and make sure this line https://github.com/YuwenXiong/py-R-FCN/blob/master/lib/fast_rcnn/train.py#L151 will be executed.

**Comment by muyue1238** [comment]
@YuwenXiong Hi, I checked my code and it's the same as the code you gave. I'm not sure it's been executed during the training process. I tried again just now and only caffemodel file were generated. Thanks for your reply!
