### ISSUE TITLE
how to using python api to generate your https://github.com/YuwenXiong/py-R-FCN/blob/master/models/pascal_voc/ResNet-50/rfcn_end2end/train_agnostic.prototxt

### ISSUE THREAD

**Issue by qinyi20060410** [Orpine/py-R-FCN#99]
hello,YuwenXiong
would you please share your python scripts of generating your network.  I want to reimplement the network based on your work.And i have some problem about how to make prototxt file. Can you give me some help or any advice?

**Comment by YuwenXiong** [comment]
The prototxt is written by hand based on https://github.com/KaimingHe/deep-residual-networks.
